language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install tox-travis
  - pip install coveralls
  - pip install -r requirements.txt
addons:
  postgresql: "10"
env:
  - TEST_POSTGRES_URL="postgres://postgres@127.0.0.1/cron_tools_aggregator_test"
before_script:
  - psql -c 'create database cron_tools_aggregator_test'
script: tox
after_success:
  - coveralls
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL